global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mcp-production'
    service: 'universal-docs'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

rule_files:
  - '/etc/prometheus/alerts/*.yml'

scrape_configs:
  # MCP Server metrics
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scheme: http
    basic_auth:
      username: 'prometheus'
      password_file: '/etc/prometheus/auth/password'

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Remote write configuration (optional)
# remote_write:
#   - url: 'https://prometheus-remote.example.com/api/v1/write'
#     basic_auth:
#       username: 'remote_user'
#       password_file: '/etc/prometheus/remote_password'
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'go_.*'
#         action: drop