groups:
  - name: mcp_server_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # API response time
      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow API response times"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      # Vector search latency
      - alert: SlowVectorSearch
        expr: histogram_quantile(0.95, rate(vector_search_duration_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Vector search is slow"
          description: "95th percentile search time is {{ $value }}s"

      # Git sync failures
      - alert: GitSyncFailures
        expr: rate(git_sync_errors_total[15m]) > 0.1
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "Git sync failures detected"
          description: "Git sync error rate is {{ $value }} per second for repository {{ $labels.repository }}"

      # Memory usage
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / (1024 * 1024 * 1024) > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Process is using {{ $value }}GB of memory"

      # Document processing backlog
      - alert: DocumentProcessingBacklog
        expr: documents_pending_total > 1000
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Large document processing backlog"
          description: "{{ $value }} documents pending processing"

      # Rate limit exhaustion
      - alert: RateLimitExhaustion
        expr: rate(rate_limit_exceeded_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate of rate limit violations"
          description: "{{ $value }} rate limit violations per second"

      # Qdrant connection issues
      - alert: QdrantConnectionFailure
        expr: up{job="qdrant"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Qdrant is down"
          description: "Cannot connect to Qdrant vector database"

      # Redis connection issues
      - alert: RedisConnectionFailure
        expr: up{job="redis"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis is down"
          description: "Cannot connect to Redis cache"

      # Disk space
      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Only {{ $value | humanizePercentage }} disk space remaining"

  - name: mcp_business_alerts
    interval: 60s
    rules:
      # Low search usage
      - alert: LowSearchUsage
        expr: rate(search_requests_total[1h]) < 0.1
        for: 2h
        labels:
          severity: info
        annotations:
          summary: "Low search activity"
          description: "Search usage is very low ({{ $value }} requests/sec)"

      # Stale documentation
      - alert: StaleDocumentation
        expr: time() - documents_last_indexed_timestamp > 86400
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Documentation not updated"
          description: "No new documents indexed for {{ $value | humanizeDuration }}"

      # Authentication failures
      - alert: HighAuthFailureRate
        expr: rate(auth_failures_total[5m]) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High authentication failure rate"
          description: "{{ $value }} authentication failures per second"