project:
  name: "Universal Documentation MCP Server"
  description: "AI-powered documentation search and context generation"
  version: "1.0.0"

server:
  port: 3000
  host: "localhost"

vectorStore:
  type: "qdrant"
  config:
    url: "http://localhost:6333"
    collection: "documentation"

repositories: []

contextGeneration:
  maxTokens: 8000
  minRelevanceScore: 0.7
  includeMetadata: true
  progressive:
    enabled: true
    levels:
      - name: "overview"
        maxChunks: 3
      - name: "detailed"
        maxChunks: 10
      - name: "comprehensive"
        maxChunks: 25
